"""Unsloth QLoRA Fine-Tuning Script.
Designed to run on a Linux environment with an NVIDIA GPU (e.g. RunPod, Google Colab).
"""

import argparse
import os
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template, standardize_sharegpt
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# Map our CLI arguments to the highly-optimized Unsloth 4-bit base models
MODEL_MAP = {
    "qwen": "unsloth/Qwen2.5-3B-Instruct",
    "phi": "unsloth/Phi-3.5-mini-instruct",
    "llama": "unsloth/Llama-3.2-3B-Instruct"
}

def main():
    parser = argparse.ArgumentParser(description="Fine-tune SLM using Unsloth")
    parser.add_argument("--model", type=str, choices=["qwen", "phi", "llama"], required=True, help="Target model family")
    parser.add_argument("--epochs", type=int, default=1, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=2, help="Batch size per device")
    parser.add_argument("--grad_accum", type=int, default=4, help="Gradient accumulation steps")
    args = parser.parse_args()

    model_name = MODEL_MAP[args.model]
    max_seq_length = 4096 # Supports long journal entries + large JSON outputs

    print(f"========== INITIALIZING {args.model.upper()} ==========")
    
    # 1. Load Model & Tokenizer in 4-bit
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_name,
        max_seq_length=max_seq_length,
        dtype=None,          # Auto-detects bf16 vs fp16
        load_in_4bit=True,   # Dramatically reduces VRAM usage
    )

    # 2. Inject LoRA Adapters
    print("Injecting LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=16, # Rank 16 is a great balance for complex JSON + Reasoning
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", 
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth", # 30% less VRAM usage
        random_state=3407,
    )

    # 3. Format Dataset
    print("Formatting dataset...")
    # Unsloth chat template names per model family
    CHAT_TEMPLATE_MAP = {
        "qwen": "chatml",
        "phi": "phi-3",
        "llama": "llama-3.1",
    }
    tokenizer = get_chat_template(tokenizer, chat_template=CHAT_TEMPLATE_MAP[args.model])
    
    def formatting_prompts_func(examples):
        convos = examples["conversations"]
        texts = [tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False) for c in convos]
        return { "text" : texts }

    # Load dataset generated by Phase 1
    dataset_path = os.path.join(os.path.dirname(__file__), "..", "output", "training_dataset.jsonl")
    dataset = load_dataset("json", data_files=dataset_path, split="train")
    
    dataset = standardize_sharegpt(dataset)
    dataset = dataset.map(formatting_prompts_func, batched=True)

    # 4. Train
    print("Starting SFT Training...")
    output_dir = os.path.join(os.path.dirname(__file__), "..", "output", f"lora_{args.model}")
    
    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        dataset_num_proc=2,
        args=TrainingArguments(
            per_device_train_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            warmup_steps=10,
            num_train_epochs=args.epochs,
            learning_rate=2e-4,
            fp16=not FastLanguageModel.is_bfloat16_supported(),
            bf16=FastLanguageModel.is_bfloat16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=output_dir,
        ),
    )
    
    trainer.train()

    # 5a. Save LoRA adapter weights (for evaluate.py to load)
    print(f"========== SAVING LORA ADAPTER ==========")
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    print(f"LoRA adapter saved to {output_dir}")

    # 5b. Export merged model as GGUF for Phase 3 (SGLang inference)
    print(f"========== EXPORTING {args.model.upper()} TO GGUF ==========")
    export_dir = os.path.join(os.path.dirname(__file__), "..", "output", f"model_{args.model}_q4_k_m")
    
    model.save_pretrained_gguf(export_dir, tokenizer, quantization_method="q4_k_m")
    
    print(f"Success! GGUF model exported to {export_dir}")

if __name__ == "__main__":
    main()
